name: "Extra build information"
description: "Expose extra context information "
author: "Epsy Engineering <engieering@epsyhealth.com>"

inputs:
  github_token:
    description: Github Token for extra GH context information
    required: true

  environment:
    description: Environment
    required: true

  cache:
    description: Use cache file between executions
    required: false
    default: false

  export:
    description: Export variable as environment variable
    required: false
    default: false

outputs:
  critical:
    description: Number of critical findings
  high:
    description: Number of high findings


runs:
  using: "docker"
  image: "Dockerfile"
