name: "Extra build information"
description: "Expose extra context information "
author: "Epsy Engineering <engieering@epsyhealth.com>"

inputs:
  github_token:
    description: Github Token for extra GH context information
    required: true

  environment:
    description: Environment
    required: true

  cache:
    description: Use cache file between executions
    required: false
    default: false

  export:
    description: Export variable as environment variable
    required: false
    default: false

  deployment_id:
    description: Deployment ID to be persisted in variables cache
    required: false

  extras:
    description: Extra variables to be passed to step in format var::value,other::value
    required: false

outputs:
  project_platform:
    description: Platform of the project
  project_package_version:
    description: Project package version pattern for given stage
  project_current_version:
    description: Version assigned to current commit
  project_python_version:
    description: Python version required by project
  project_release_previous:
    description: Previous version semantic number
  project_release_previous_tag:
    description: Tag associated with previous version
  project_release_name:
    description: Relase name associated with current commit
  project_release_body:
    description: Relase description associated with current commit
  project_release_body_json:
    description: Json friendly release description
  project_release_id:
    description: Relase id associated with current commit
  project_release_url:
    description: GitHub URL pointing to the release
  project_current_deployment_id:
    description: Deployment id associated with current flow
  project_active_deployment_id:
    description: Active deployment id associated with specified environment
  project_active_deployment_sha:
    description: Active deployment commit sha associated with specified environment
  project_previous_deployment_id:
    description: Previous deployment id associated with specified environment
  project_previous_deployment_sha:
    description: Previous deployment commit sha associated with specified environment
  project_environment:
    description: Associated context environment
  project_project_id:
    description: Alphanumeric project id generated baseed on the repository name


runs:
  using: "docker"
  image: "docker://epsyhealth/action-context"
